import {defaultProject,holeLayouts} from './defaults.js';
import {translations,languageNames,phraseTranslations} from './i18n.js';

const clone=o=>JSON.parse(JSON.stringify(o));
const BUILD_VERSION='2026.09.04.5';
const ART=window.GAME_ART||{};
const savedRaw=localStorage.getItem('whackProject');
let project=(()=>{try{return {...clone(defaultProject),...JSON.parse(savedRaw)}}catch{return clone(defaultProject)}})();
try{if(location.hash.startsWith('#p='))project={...clone(defaultProject),...JSON.parse(decodeURIComponent(escape(atob(location.hash.slice(3)))))} }catch{}
project.design={...clone(defaultProject.design),...(project.design||{}),hud:{...clone(defaultProject.design.hud),...(project.design?.hud||{})},screens:{...clone(defaultProject.design.screens),...(project.design?.screens||{})}};
Object.keys(defaultProject.design.screens).forEach(k=>project.design.screens[k]={...clone(defaultProject.design.screens[k]),...(project.design.screens[k]||{})});
if(!project.game.lifeIcon)project.game.lifeIcon='❤️';
project.screens={...clone(defaultProject.screens),...(project.screens||{})};
project.sounds={...clone(defaultProject.sounds),...(project.sounds||{})};
project.integrations={...clone(defaultProject.integrations),...(project.integrations||{})};
if(!['adventure','tropics','desert','space','water','fantasy'].includes(project.background?.preset)){project.background={...(project.background||{}),preset:'adventure'}}
if(project.characters?.[0]?.emoji==='🦫')project.characters[0].emoji='🐹';
if(project.characters?.[0]&&project.characters[0].artIndex===undefined)project.characters[0].artIndex=0;
if(project.characters?.[1]&&project.characters[1].artIndex===undefined)project.characters[1].artIndex=1;
if(project.characters?.[2]&&project.characters[2].toolArtIndex===undefined)project.characters[2].toolArtIndex=0;
project.characters?.forEach(c=>delete c.teenIndex);
if(project.hitItem.toolArtIndex===undefined)project.hitItem.toolArtIndex=3;
if(!project.hitItem.exitAnimation)project.hitItem.exitAnimation='sink';
project.editorLayout={...clone(defaultProject.editorLayout),...(project.editorLayout||{}),hero:{...clone(defaultProject.editorLayout.hero),...(project.editorLayout?.hero||{})},danger:{...clone(defaultProject.editorLayout.danger),...(project.editorLayout?.danger||{})},hammer:{...clone(defaultProject.editorLayout.hammer),...(project.editorLayout?.hammer||{})}};
let ui={tab:'design',objectTool:'hero',screen:'title',testing:false,gameState:'TITLE',score:0,lives:project.game.lives,time:project.game.duration,active:[],question:null,selected:[],fx:null,hammer:null,hammerCursor:{x:88,y:82},hammerHeld:false,save:'Сохранено',emojiCatalog:[],emojiResults:[],emojiLoading:false,emojiError:''};
let history=[clone(project)],historyIndex=0,spawnTimer,countdown;
const embedded=new URLSearchParams(location.search).get('mode')==='game';
if(embedded)document.body.classList.add('embedded');
const $=s=>document.querySelector(s);

const t=k=>translations.ru[k]||k;
const gt=k=>(translations[project.meta.language]||translations.ru)[k]||translations.ru[k]||k;
const tabs=[['design','🎨','design'],['game','🎮','game'],['characters','🦫','characters'],['hammer','🔨','hammer'],['spawn','⏱','spawn'],['questions','❓','questions'],['screens','🖥','screens'],['settings','⚙','settings']];
const backgrounds={adventure:['Приключение','#142815'],tropics:['Тропики','#137ca0'],desert:['Пустыня','#b96c2a'],space:['Космос','#21104f'],water:['Подводный мир','#087f9e'],fantasy:['Фантазия','#6c52b9']};
const notoGif=code=>`https://fonts.gstatic.com/s/e/notoemoji/latest/${code}/512.gif`;
const animatedEmojis={hero:[['Лягушка','1f438'],['Лиса','1f98a'],['Медведь','1f43b'],['Лев','1f981'],['Черепаха','1f422'],['Панда','1f43c'],['Корова','1f42e'],['Единорог','1f984'],['Волк','1f43a'],['Дракон','1f409'],['Динозавр','1f996'],['Кролик','1f407'],['Крыса','1f400'],['Собака','1f415'],['Лошадь','1f40e'],['Козлёнок','1f410'],['Ленивец','1f9a5'],['Кенгуру','1f998'],['Тигр','1f405'],['Обезьяна','1f412'],['Горилла','1f98d'],['Енот','1f99d'],['Ёжик','1f994'],['Выдра','1f9a6'],['Сова','1f989'],['Пингвин','1f427'],['Дельфин','1f42c'],['Акула','1f988']],danger:[['Бомба','1f4a3'],['Огонь','1f525'],['Молния','26a1'],['Череп','1f480'],['Привидение','1f47b'],['Пришелец','1f47d'],['Монстр','1f47e'],['Злой демон','1f47f'],['Вулкан','1f30b'],['Торнадо','1f32a_fe0f'],['Циклон','1f300'],['Гроза','1f329_fe0f'],['Комета','2604_fe0f'],['Кактус','1f335'],['Крокодил','1f40a'],['Змея','1f40d'],['Тираннозавр','1f996'],['Огр','1f479']]};
function backgroundPreview(key,fallback){return ART.backgrounds?.[key]?`url(${ART.backgrounds[key]}) center/cover`:fallback}
function stageBackground(){if(project.background.custom)return `background-image:url(${project.background.custom});background-size:${project.background.fit};background-position:center`;const image=ART.backgrounds?.[project.background.preset];return image?`background-image:url(${image});background-size:cover;background-position:center`:''}
const holePalettes={stones:['#a77a52','#52351f','#160e0a'],neon:['#c66cff','#44226f','#050313'],grass:['#76d94f','#326f31','#160d08'],portal:['#50daf4','#704bff','#04051e'],snow:['#f2fdff','#86cee7','#183044'],lava:['#ffb000','#df3b00','#190300']};
function holeAsset(style){if(ART.holes?.[style])return ART.holes[style];const [rim,mid,dark]=holePalettes[style]||holePalettes.stones,svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 170"><ellipse cx="150" cy="86" rx="145" ry="76" fill="${rim}"/><ellipse cx="150" cy="84" rx="105" ry="49" fill="${mid}"/><ellipse cx="150" cy="80" rx="82" ry="34" fill="${dark}"/></svg>`;return `data:image/svg+xml,${encodeURIComponent(svg)}`}
function atlasStyle(kind,index){const col=index%3,row=Math.floor(index/3),x=col*50,y=row*100;return `background-image:url(${ART[kind]});background-size:300% 200%;background-position:${x}% ${y}%;background-repeat:no-repeat`}

function save(push=true){ui.save='Сохранение…';if(push){history=history.slice(0,historyIndex+1);history.push(clone(project));historyIndex=history.length-1}renderTop();clearTimeout(save.t);save.t=setTimeout(()=>{localStorage.setItem('whackProject',JSON.stringify(project));ui.save='Сохранено';renderTop()},450)}
function set(path,value,push=true){let o=project;const keys=path.split('.');keys.slice(0,-1).forEach(k=>o=o[k]);o[keys.at(-1)]=value;save(push);render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function field(label,path,type='text',extra=''){const value=path.split('.').reduce((o,k)=>o[k],project);return `<label class="field"><span>${label}</span><input type="${type}" data-path="${path}" value="${esc(value)}" ${extra}></label>`}
function toggle(label,path){const v=path.split('.').reduce((o,k)=>o[k],project);return `<div class="toggle-row"><span>${label}</span><button class="toggle ${v?'on':''}" data-toggle="${path}"></button></div>`}
function card(title,body){return `<section class="card"><div class="card-head">${title}</div><div class="card-body">${body}</div></section>`}
function exitOptions(){return `<label class="field"><span>Анимация цели после удара</span><select data-path="hitItem.exitAnimation"><option value="sink" ${project.hitItem.exitAnimation==='sink'?'selected':''}>Провалиться в лунку</option><option value="spin" ${project.hitItem.exitAnimation==='spin'?'selected':''}>Закрутиться</option><option value="pop" ${project.hitItem.exitAnimation==='pop'?'selected':''}>Лопнуть</option><option value="fly" ${project.hitItem.exitAnimation==='fly'?'selected':''}>Улететь вверх</option><option value="shake" ${project.hitItem.exitAnimation==='shake'?'selected':''}>Встряхнуться</option><option value="fade" ${project.hitItem.exitAnimation==='fade'?'selected':''}>Раствориться</option></select></label>`}

function render(){const oldSidebar=document.querySelector('.sidebar'),scrollTop=oldSidebar?.scrollTop||0;document.querySelector('#app').innerHTML=`<div class="app"><header class="topbar" id="top"></header><main class="workspace"><aside class="sidebar"><nav class="tabs">${tabs.map(x=>`<button class="tab ${ui.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]} ${t(x[2])}</button>`).join('')}</nav><div class="panel" id="panel"></div><footer class="copyright">${t('footer')}</footer></aside><section class="preview-pane" id="preview"></section></main></div><div id="overlay"></div>`;renderTop();renderPanel();renderPreview();bind();typesetMath();const sidebar=document.querySelector('.sidebar');if(sidebar)sidebar.scrollTop=scrollTop}
function renderTop(){const el=$('#top');if(!el)return;el.innerHTML=`<div class="brand"><div class="logo">🔨</div><div><strong>${t('brand')}</strong><small>${t('editor')}</small></div></div><label class="language-select">🌐 <select id="language">${Object.entries(languageNames).map(([k,v])=>`<option value="${k}" ${project.meta.language===k?'selected':''}>${v}</option>`).join('')}</select></label><span class="save">● ${ui.save==='Сохранение…'?t('saving'):t('saved')}</span><div class="top-actions"><button class="btn icon" data-action="undo" title="Undo">↶</button><button class="btn icon" data-action="redo" title="Redo">↷</button><button class="btn" data-action="project"><span class="hide-sm">${t('project')}</span> ▾</button><button class="btn" data-action="download">${t('download')}</button><button class="btn" data-action="lighten">⚡ Облегчить код</button><button class="btn pink" data-action="genially">${t('genially')}</button></div>`}

function renderPanel(){let html='';
 if(ui.tab==='design') html=`<div class="eyebrow">Оформление</div><h2>Вид игры</h2>${card('Библиотека фоновых картинок',`<div class="background-grid">${Object.entries(backgrounds).map(([k,v])=>`<button class="background-card ${project.background.preset===k?'active':''}" data-bg="${k}" style="background:${backgroundPreview(k,v[1])}"><span>${v[0]}</span></button>`).join('')}</div>`)}${card('Цвета и форма',`${field('Акцентный цвет','design.accent','color')} ${field('Цвет кнопок','design.button','color')} ${field('Скругление','design.radius','range','min="4" max="40" class="range"')}`)}${card('Свой фон',`<label class="upload">＋ Загрузить PNG, JPG, WebP или GIF<input hidden type="file" data-upload="background" accept="image/png,image/jpeg,image/webp,image/gif"></label>`)}`;
 if(ui.tab==='game') html=`<div class="eyebrow">Игровое поле</div><h2>Лунки и фон</h2>${card('Количество лунок',`<div class="row"><select id="holes">${[3,4,6,8,9,12].map(n=>`<option ${project.holes.length===n?'selected':''}>${n}</option>`).join('')}</select><button class="btn" data-action="add-hole">＋ Место</button></div><p class="label" style="margin-top:12px">Перетаскивайте лунки прямо в предпросмотре.</p>`)}${card('Библиотека прозрачных лунок',`<div class="asset-grid">${[['stones','Камни'],['neon','Неон'],['grass','Трава'],['portal','Портал'],['snow','Снег'],['lava','Лава'],['crystal','Кристаллы'],['tech','Техно'],['jungle','Джунгли'],['metal','Металл']].map(x=>`<button class="asset hole-card ${project.design.holeStyle===x[0]?'active':''}" data-hole-style="${x[0]}"><img src="${holeAsset(x[0])}" alt="${x[1]}"><small>${x[1]}</small></button>`).join('')}</div>`)}${card('Масштаб фона',`<label class="field"><span>Режим</span><select data-path="background.fit"><option value="cover">Заполнить</option><option value="contain">Вместить</option><option value="100% 100%">Растянуть</option></select></label>`)}`;
 if(ui.tab==='characters') html=`<div class="eyebrow">GIF‑эмодзи без API</div><h2>${ui.objectTool==='danger'?'Препятствия':'Герой'}</h2>${emojiGifLibrary()}${card('Настройки выбранного объекта',`${field('Название',`characters.${ui.objectTool==='danger'?2:0}.name`)}<div class="row">${field('Очки',`characters.${ui.objectTool==='danger'?2:0}.points`,'number')}${field('Масштаб',`characters.${ui.objectTool==='danger'?2:0}.scale`,'range','min="0.6" max="1.5" step="0.1"')}</div>${exitOptions()}`)}${card('Своя GIF-анимация',`<label class="upload">＋ Загрузить GIF<input hidden type="file" data-upload="character" accept="image/gif,image/webp"></label><label class="field" style="margin-top:12px"><span>Прямая ссылка на GIF</span><input id="gifUrl" placeholder="https://…/animation.gif"></label><button class="btn" data-action="add-gif-url">Добавить GIF</button>`)}`;
 if(ui.tab==='hammer') html=`<div class="eyebrow">Премиальная графика</div><h2>Предмет удара</h2>${card('Библиотека прозрачных молотов',`<div class="asset-grid">${(ART.hammers||[]).map(h=>`<button class="asset art-asset ${project.hitItem.image===h.url?'active':''}" data-hammer-url="${h.url}" data-name="${h.name}"><img class="transparent-tool" src="${h.url}" alt="${h.name}"><small>${h.name}</small></button>`).join('')}</div><label class="upload" style="display:block;margin-top:12px">＋ Загрузить свой GIF-молоток<input hidden type="file" data-upload="hammer" accept="image/png,image/webp,image/gif"></label>`)}${card('Размер и скорость удара',`${field('Размер молотка','hitItem.size','range','min="50" max="320" class="range"')}${field('Длительность, мс','hitItem.duration','range','min="180" max="900" class="range"')}`)} `;
 if(ui.tab==='spawn') html=`<div class="eyebrow">Динамика</div><h2>Появления</h2>${card('Режим',`<div class="row"><button class="btn ${project.spawnSettings.mode==='random'?'primary':''}" data-mode="random">Случайно</button><button class="btn ${project.spawnSettings.mode==='timeline'?'primary':''}" data-mode="timeline">Сценарий</button></div>`)}${project.spawnSettings.mode==='random'?card('Случайные появления',`${field('Минимальный интервал, мс','spawnSettings.minInterval','number')}${field('Максимальный интервал, мс','spawnSettings.maxInterval','number')}${field('Видимость, мс','spawnSettings.visibleFor','number')}${field('Одновременно','spawnSettings.maxActive','number')}`):card('Сценарий',`${project.spawnTimeline.map((e,i)=>`<div class="timeline-row"><input style="width:56px" type="number" value="${e.time}" data-timeline="${i}:time"><span>сек →</span><select data-timeline="${i}:character">${project.characters.map(c=>`<option value="${c.id}" ${e.character===c.id?'selected':''}>${c.emoji}</option>`).join('')}</select><input style="width:50px" type="number" value="${e.hole+1}" data-timeline="${i}:hole"><button class="mini" data-del-timeline="${i}">×</button></div>`).join('')}<button class="btn" data-action="add-spawn">＋ Добавить появление</button>`)}`;
 if(ui.tab==='questions') html=questionsPanel();
 if(ui.tab==='screens') html=`<div class="eyebrow">Тексты и оформление</div><h2>Все экраны игры</h2>${card('Титульный экран',`${field('Название игры','meta.title')}${field('Подзаголовок','screens.subtitle')}<label class="field"><span>Инструкция</span><textarea data-path="screens.instruction">${esc(project.screens.instruction)}</textarea></label>${field('Название кнопки','screens.playButton')}${appearanceFields('title')}`)}${card('Окно задания',`${appearanceFields('question')}${field('Фон плашки ответа','design.screens.question.answerBackground','color')}${field('Фон поля ввода','design.screens.question.inputBackground','color')}`)}${card('Окно «Правильно»',`${field('Заголовок','screens.correctTitle')}${appearanceFields('correct')}`)}${card('Окно «Ошибка»',`${field('Заголовок','screens.wrongTitle')}${appearanceFields('wrong')}`)}${card('Экран победы',`${field('Заголовок','screens.winTitle')}${appearanceFields('win')}`)}${card('Экран поражения',`${field('Заголовок','screens.loseTitle')}${appearanceFields('lose')}`)}`;
 if(ui.tab==='settings') html=`<div class="eyebrow">Правила</div><h2>Параметры игры</h2>${card('Основное',`${field('Время игры, сек','game.duration','number')}${field('Количество жизней','game.lives','number')}${field('Очков для победы','game.targetScore','number')}`)}${card('Игровой интерфейс',`${toggle('Показывать таймер','game.showTimer')}${toggle('Показывать очки','game.showScore')}${toggle('Показывать жизни','game.showLives')}${toggle('Пауза во время вопроса','game.pauseDuringQuestion')}<label class="field"><span>Значок жизней</span><select data-path="game.lifeIcon">${['❤️','💚','💙','💜','🧡','⭐','🔥','🛡️','⚡','💎'].map(x=>`<option ${project.game.lifeIcon===x?'selected':''}>${x}</option>`).join('')}</select></label>${field('Фон показателей','design.hud.background','color')}${field('Цвет текста','design.hud.text','color')}${field('Рамка таймера','design.hud.timerBorder','color')}${field('Рамка очков','design.hud.scoreBorder','color')}${field('Рамка жизней','design.hud.livesBorder','color')}`)}${card('Звуковые эффекты',`${toggle('Включить звук','sounds.enabled')}${field('Громкость','sounds.volume','range','min="0" max="1" step="0.05" class="range"')}${toggle('Появление','sounds.spawn')}${toggle('Удар','sounds.hit')}${toggle('Правильный ответ','sounds.correct')}${toggle('Ошибка','sounds.wrong')}${toggle('Победа','sounds.win')}${toggle('Поражение','sounds.lose')}<button class="btn" data-action="sound-test">▶ Проверить звук</button>`)}`;
 $('#panel').innerHTML=html;localizeUI($('#panel'));
}
function appearanceFields(name){const fonts=['Manrope','Arial','Georgia','Trebuchet MS','Courier New','Verdana','Tahoma','Impact','Comic Sans MS','Times New Roman','Montserrat','Roboto Slab','Playfair Display','Oswald','Nunito'];return `<div class="style-grid"><label class="field"><span>Шрифт</span><select data-path="design.screens.${name}.font">${fonts.map(f=>`<option ${project.design.screens[name].font===f?'selected':''}>${f}</option>`).join('')}</select></label>${field('Размер заголовка',`design.screens.${name}.titleSize`,'range','min="20" max="80" class="range"')}${field('Цвет текста',`design.screens.${name}.text`,'color')}${field('Фон окна',`design.screens.${name}.background`,'color')}${field('Цвет рамки',`design.screens.${name}.border`,'color')}${field('Свечение окна',`design.screens.${name}.glow`,'color')}${field('Цвет кнопки',`design.screens.${name}.button`,'color')}${field('Текст кнопки',`design.screens.${name}.buttonText`,'color')}${field('Свечение кнопки',`design.screens.${name}.buttonGlow`,'color')}</div>`}
function localizeUI(){/* Язык меняет только интерфейс игры; редактор всегда русский. */}
function questionsPanel(){return `<div class="eyebrow">Учебный контент</div><h2>Банк заданий</h2>${project.questions.map((q,i)=>`<div class="question-item"><span>${q.type==='input'?'⌨️':q.type==='multiple'?'☑️':q.type==='order'?'↕️':'🔘'}</span><div class="grow"><strong>Задание ${i+1}</strong><small>${esc(q.text)}</small></div><button class="mini" data-edit-q="${i}">✎</button><button class="mini" data-copy-q="${i}">⧉</button><button class="mini" data-del-q="${i}">×</button></div>`).join('')}<button class="btn primary" data-action="add-question">＋ Добавить задание</button>`}
function emojiGifLibrary(){const danger=ui.objectTool==='danger',items=animatedEmojis[danger?'danger':'hero'];return card(danger?'Большая библиотека препятствий':'Большая библиотека героев',`<div class="gif-grid">${!danger&&ART.premiumMole?`<button class="gif-item premium-item" data-emoji-gif="${ART.premiumMole}" data-name="Крот" title="Крот"><img src="${ART.premiumMole}" alt="Крот"><small>Крот</small></button>`:''}${items.map(([name,code])=>`<button class="gif-item" data-emoji-gif="${notoGif(code)}" data-name="${esc(name)}" title="${esc(name)}"><img src="${notoGif(code)}" alt="${esc(name)}" loading="lazy"><small>${esc(name)}</small></button>`).join('')}</div><p class="library-status">Рабочие анимированные персонажи Google Noto и встроенный крот.</p><div class="giphy-credit">ANIMATED EMOJI BY GOOGLE NOTO</div>`)}

function renderPreview(){const screens=[['game','🎮','play'],['title','🏠','title'],['question','❓','question'],['correct','✅','correct'],['wrong','❌','wrong'],['win','🏆','win'],['lose','💔','lose']];$('#preview').innerHTML=`<div class="preview-head"><div><div class="eyebrow">👁 ${t('preview')}</div><h1>${t('student')}</h1></div><div class="preview-actions"><button class="btn green">${ui.testing?t('testing'):t('edit')}</button><button class="btn primary" data-action="test">${ui.testing?'■ '+t('stop'):'▶ '+t('test')}</button></div></div><div class="preview-toolbar"><button data-object="hero" class="object-chip ${ui.objectTool==='hero'?'active':''}">Герой</button><button data-object="danger" class="object-chip danger ${ui.objectTool==='danger'?'active':''}">Препятствия</button><button data-object="holes" class="object-chip ${ui.objectTool==='holes'?'active':''}">Лунки</button>${screens.map(s=>`<button class="screen-btn ${ui.screen===s[0]?'active':''}" data-screen="${s[0]}">${s[1]} ${t(s[2])}</button>`).join('')}</div><div class="stage-shell"><div class="stage bg-${project.background.preset}" id="stage" style="${stageBackground()};--accent:${project.design.accent};border-radius:${project.design.radius/2}px">${stageHTML()}</div></div><div class="hint">Зелёную рамку можно перетаскивать; тяните угол для изменения размера</div>`;localizeUI($('#preview'));bindStageDrag();bindHammerControl();bindSelectionControl();typesetMath()}
function typesetMath(){document.body.dataset.holeStyle=project.design.holeStyle||'stones';const bar=document.querySelector('.preview-toolbar');if(bar&&!bar.querySelector('[data-screen="hud"]')){const b=document.createElement('button');b.className='screen-btn'+(ui.screen==='hud'?' active':'');b.dataset.screen='hud';b.textContent='📊 Интерфейс';bar.insertBefore(b,bar.querySelector('[data-screen="game"]'))}clearTimeout(typesetMath.t);typesetMath.t=setTimeout(()=>window.MathJax?.typesetPromise?.([$('#preview')]).catch(()=>{}),40)}
function hudStyle(kind){const h=project.design.hud,b=h[kind+'Border']||h.border;return `background:${h.background}e8;color:${h.text};border-color:${b}`}
function stageHTML(){if(ui.screen==='title'||(ui.testing&&ui.gameState==='TITLE'))return titleHTML();if(['win','lose'].includes(ui.screen)||['WIN','LOSE'].includes(ui.gameState))return endHTML(ui.screen==='lose'||ui.gameState==='LOSE');if(ui.screen==='question'&&!ui.question)ui.question=project.questions[0];const shownHammer=ui.hammer||(ui.testing&&ui.gameState==='PLAYING'?ui.hammerCursor:null),selection=!ui.testing&&ui.screen==='game'?(ui.tab==='hammer'?selectionHTML('hammer',project.hitItem):ui.objectTool==='hero'?selectionHTML('hero',project.characters[0]):''):'';return `<div class="game-hud">${project.game.showTimer?`<div class="hud-pill" style="${hudStyle('timer')}">⏱ ${fmt(ui.testing?ui.time:23)}</div>`:''}${project.game.showScore?`<div class="hud-pill" style="${hudStyle('score')}">⭐ ${ui.testing?ui.score:40}</div>`:''}${project.game.showLives?`<div class="hud-pill" style="${hudStyle('lives')}">${project.game.lifeIcon} ${ui.testing?ui.lives:project.game.lives}</div>`:''}</div>${project.holes.map((h,i)=>`<div class="hole ${!ui.testing?'edit':''}" data-hole="${i}" style="left:${h.x}%;top:${h.y}%;background-image:url('${holeAsset(project.design.holeStyle)}')"></div>${moleAt(i,h)}`).join('')}${selection}${ui.question||ui.screen==='question'?questionHTML():''}${ui.screen==='correct'?feedbackHTML(true):''}${ui.screen==='wrong'?feedbackHTML(false):''}${ui.fx?`<div class="hit-fx" style="left:${ui.fx.x}%;top:${ui.fx.y}%">${ui.fx.text}</div>`:''}${shownHammer?`<div class="hammer player-hammer ${ui.hammerHeld?'held':''}" data-hammer-control style="left:${shownHammer.x}%;top:${shownHammer.y}%;width:${Math.max(7,Math.min(40,project.hitItem.size/8))}%">${visual(project.hitItem)}</div>`:''}`}
function selectionHTML(kind,item){const p=project.editorLayout[kind],preview=kind==='hero'&&ui.tab==='characters'?` preview-exit-${project.hitItem.exitAnimation}`:'';return `<div class="selection-box" data-selection="${kind}" style="left:${p.x}%;top:${p.y}%;width:${p.size}%"><div class="selection-art${preview}">${visual(item)}</div><i class="resize-handle" data-resize="${kind}"></i></div>`}
function visual(c){if(c.image)return `<img src="${c.image}" class="custom-art">`;if(c===project.hitItem&&ART.premiumHammer)return `<img src="${ART.premiumHammer}" class="custom-art">`;if(c.id==='mole'&&ART.premiumMole)return `<img src="${ART.premiumMole}" class="custom-art">`;if(c.toolArtIndex!==undefined&&ART.tools)return `<span class="game-sprite" style="${atlasStyle('tools',c.toolArtIndex)}"></span>`;if(c.artIndex!==undefined&&ART.characters)return `<span class="game-sprite" style="${atlasStyle('characters',c.artIndex)}"></span>`;return c.emoji||'🎭'}
function moleAt(i,h){const a=ui.active.find(x=>x.hole===i);if(!a&&!ui.testing){if(ui.objectTool==='hero'||ui.objectTool==='holes'||ui.tab==='hammer'||i!==Math.min(1,project.holes.length-1))return'';const c=project.characters.find(x=>x.kind==='danger')||project.characters[2];if(ui.objectTool==='danger')return selectionHTML('danger',c);return `<div class="mole-wrap editor-object" style="left:${h.x}%;top:${h.y}%;transform:translate(-50%,-68%) scale(${c.scale})"><div class="mole up">${visual(c)}</div></div>`}if(!a)return'';const c=project.characters.find(x=>x.id===a.char);return `<div class="mole-wrap" style="left:${h.x}%;top:${h.y}%;transform:translate(-50%,-68%) scale(${c.scale})"><div class="mole up ${a.hit?'hit exit-'+project.hitItem.exitAnimation:''}" data-hit="${a.id}" style="--exit-duration:${project.hitItem.duration}ms">${visual(c)}</div></div>`}
function boxStyle(name){const s=project.design.screens?.[name]||defaultProject.design.screens[name];return `font-family:${s.font};color:${s.text};background:${s.background};border-color:${s.border};box-shadow:0 0 42px ${s.glow}88`}
function headingStyle(name){const s=project.design.screens?.[name]||defaultProject.design.screens[name];return `font-size:${s.titleSize}px;color:${s.text}`}
function buttonStyle(name){const s=project.design.screens?.[name]||defaultProject.design.screens[name];return `background:${s.button};color:${s.buttonText};box-shadow:0 8px 22px ${s.buttonGlow}88`}
function titleHTML(){return `<div class="title-screen"><div class="hero-card" style="${boxStyle('title')}"><div class="mascot-pop title-mascot">${visual(project.characters[0])}</div><h2 style="${headingStyle('title')}">${esc(project.meta.title)}</h2><p>${esc(project.screens.subtitle)}</p><p style="font-size:12px">${esc(project.screens.instruction)}</p><button class="big-btn" style="${buttonStyle('title')}" data-action="play">${esc(project.screens.playButton)}</button></div></div>`}
function endHTML(lose=false){const n=lose?'lose':'win';return `<div class="end-screen"><div class="hero-card" style="${boxStyle(n)}"><div style="font-size:52px">${lose?'💔':'🏆'}</div><h2 style="${headingStyle(n)}">${esc(lose?project.screens.loseTitle:project.screens.winTitle)}</h2><p>${gt('result')}: <strong>${ui.score}</strong> ${gt('points')}</p><button class="big-btn" style="${buttonStyle(n)}" data-action="play">${gt('again')}</button></div></div>`}
function questionHTML(){const q=ui.question||project.questions[0];if(!q)return'';const s=project.design.screens.question,input=q.type==='input'?`<input class="question-input" style="background:${s.inputBackground}" id="answerInput" placeholder="${gt('answerPlaceholder')}">`:`<div class="answers">${q.options.map(o=>`<button class="answer ${ui.selected.includes(o)?'selected':''}" style="background:${s.answerBackground}" data-answer="${esc(o)}">${q.type==='order'&&ui.selected.includes(o)?`${ui.selected.indexOf(o)+1}. `:''}${esc(o)}</button>`).join('')}</div>`;return `<div class="question-modal"><div class="question-card" style="${boxStyle('question')}"><h3>❓ ${gt('task')}</h3><h2 style="${headingStyle('question')}">${esc(q.text)}</h2>${input}<button class="btn primary" style="margin-top:14px;width:100%;${buttonStyle('question')}" data-action="check">${gt('check')}</button></div></div>`}
function feedbackHTML(ok){const n=ok?'correct':'wrong';return `<div class="question-modal"><div class="question-card" style="text-align:center;${boxStyle(n)}"><div style="font-size:52px">${ok?'✅':'❌'}</div><h2 style="${headingStyle(n)}">${esc(ok?project.screens.correctTitle:project.screens.wrongTitle)}</h2><p>${ok?'+20 очков':'Будь внимательнее'}</p></div></div>`}
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

function updateControl(target){const p=target.dataset.path;if(!p)return;const v=target.type==='number'||target.type==='range'?+target.value:target.value;let o=project,ks=p.split('.');ks.slice(0,-1).forEach(k=>o=o[k]);o[ks.at(-1)]=v;if(p==='hitItem.size')project.editorLayout.hammer.size=Math.max(10,Math.min(58,v/5));if(p==='characters.0.scale')project.editorLayout.hero.size=14*v;if(p==='characters.2.scale')project.editorLayout.danger.size=14*v;if(p.startsWith('design.hud.')||p==='game.lifeIcon')ui.screen='hud';else if(p==='hitItem.exitAnimation'){ui.tab='characters';ui.screen='game'}else if(p.startsWith('design.screens.'))ui.screen=ks[2];else if(p.startsWith('screens.correct'))ui.screen='correct';else if(p.startsWith('screens.wrong'))ui.screen='wrong';else if(p.startsWith('screens.win'))ui.screen='win';else if(p.startsWith('screens.lose'))ui.screen='lose';else if(p.startsWith('screens.')||p==='meta.title'||p==='meta.subtitle')ui.screen='title';save(false);renderPreview()}
function bind(){if(bind.ready)return;bind.ready=true;
 document.addEventListener('pointerdown',unlockAudio,{capture:true,once:true});
 document.addEventListener('click',e=>{const t=e.target.closest('button,[data-upload]');if(!t)return;
  if(t.dataset.tab){ui.tab=t.dataset.tab;const map={game:'game',characters:'game',hammer:'game',spawn:'game',questions:'question',screens:'title'};if(map[ui.tab]){ui.screen=map[ui.tab];ui.question=null}renderPanel();renderPreview();return}
  if(t.dataset.screen){ui.screen=t.dataset.screen;ui.question=null;renderPreview();return}if(t.dataset.object){ui.objectTool=t.dataset.object;ui.screen='game';ui.tab=t.dataset.object==='holes'?'game':'characters';render();return}
  if(t.dataset.emojiGif){applyGif(t.dataset.emojiGif,t.dataset.name);return}if(t.dataset.bg){project.background.custom=null;set('background.preset',t.dataset.bg);return}if(t.dataset.holeStyle){project.design.holeStyle=t.dataset.holeStyle;save();render();return}
  if(t.dataset.hammerUrl){project.hitItem.image=t.dataset.hammerUrl;delete project.hitItem.toolArtIndex;project.hitItem.name=t.dataset.name;save();render();return}
  if(t.dataset.mode){set('spawnSettings.mode',t.dataset.mode);return}if(t.dataset.toggle){const p=t.dataset.toggle,v=p.split('.').reduce((o,k)=>o[k],project);set(p,!v);return}if(t.dataset.answer){selectAnswer(t.dataset.answer);return}
  if(t.dataset.editQ!==undefined){questionDialog(+t.dataset.editQ);return}if(t.dataset.copyQ!==undefined){project.questions.splice(+t.dataset.copyQ+1,0,{...clone(project.questions[+t.dataset.copyQ]),id:crypto.randomUUID()});save();render();return}if(t.dataset.delQ!==undefined){project.questions.splice(+t.dataset.delQ,1);save();render();return}if(t.dataset.delTimeline!==undefined){project.spawnTimeline.splice(+t.dataset.delTimeline,1);save();render();return}
  if(t.dataset.hammerArt!==undefined){Object.assign(project.hitItem,{toolArtIndex:+t.dataset.hammerArt,name:t.dataset.name});delete project.hitItem.image;save();render();return}if(t.dataset.hit&&ui.testing){hit(t.dataset.hit,e);return}if(t.dataset.action)action(t.dataset.action)
 },true);
 document.addEventListener('input',e=>{if(e.target.dataset.path)updateControl(e.target);if(e.target.id==='holes'){project.holes=clone(holeLayouts[e.target.value]);save();render()}},true);
 document.addEventListener('change',e=>{if(e.target.id==='language'){project.meta.language=e.target.value;save();render();return}if(e.target.dataset.path&&e.target.tagName==='SELECT')updateControl(e.target);if(e.target.dataset.upload)upload(e.target,e.target.dataset.upload);if(e.target.dataset.timeline){const [i,k]=e.target.dataset.timeline.split(':');project.spawnTimeline[i][k]=k==='character'?e.target.value:+e.target.value-(k==='hole'?1:0);save();render()}},true);
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1)}},true)
}
function action(a){if(a==='test')ui.testing?stopGame():startGame();if(a==='play')startPlaying();if(a==='check')checkAnswer();if(a==='undo')undo(-1);if(a==='redo')undo(1);if(a==='lighten')lightenCode();if(a==='genially')exportDialog();if(a==='download')downloadHTML();if(a==='project')projectDialog();if(a==='sound-test')sound('correct');if(a==='search-emoji')searchAnimatedEmoji();if(a==='add-gif-url'){const url=$('#gifUrl')?.value.trim();if(!/^https:\/\/.+\.(gif|webp)(\?.*)?$/i.test(url||''))return toast('Укажите прямую HTTPS-ссылку на GIF');applyGif(url,'Своя GIF');}if(a==='add-hole'){project.holes.push({x:50,y:50});save();render()}if(a==='add-question')questionDialog(-1);if(a==='add-spawn'){project.spawnTimeline.push({time:10,character:'mole',hole:0});save();render()}}
async function searchAnimatedEmoji(){const q=($('#emojiSearch')?.value||'').trim().toLowerCase();ui.emojiLoading=true;ui.emojiError='';renderPanel();try{if(!ui.emojiCatalog.length){const response=await fetch('https://googlefonts.github.io/noto-emoji-animation/data/api.json');if(!response.ok)throw new Error(`Ошибка ${response.status}`);const json=await response.json();ui.emojiCatalog=json.icons||[]}ui.emojiResults=ui.emojiCatalog.filter(x=>!q||[x.name,x.codepoint,...(x.tags||[]),...(x.categories||[])].join(' ').toLowerCase().includes(q)).map(x=>({codepoint:x.codepoint,label:(x.tags?.[0]||x.name).replaceAll(':','').replaceAll('-',' ')})).slice(0,48);if(!ui.emojiResults.length)ui.emojiError='Ничего не найдено. Попробуйте запрос на английском.'}catch(error){ui.emojiError=`Каталог не загрузился: ${error.message}`}finally{ui.emojiLoading=false;renderPanel()}}
function applyGif(url,name){const target=ui.objectTool==='danger'?(project.characters.find(c=>c.kind==='danger')||project.characters[2]):project.characters[0];target.image=url;target.name=name||target.name;delete target.artIndex;delete target.toolArtIndex;save();render();toast('GIF выбрана и показана в лунке')}
function lightenCode(){const before=new Blob([JSON.stringify(project)]).size;project.assets=[];project.questions.forEach(q=>{delete q.media});const after=new Blob([JSON.stringify(project)]).size;save();render();toast(`Код оптимизирован: ${Math.max(0,Math.round((1-after/before)*100))}% легче`)}
function undo(dir){const n=historyIndex+dir;if(n<0||n>=history.length)return;historyIndex=n;project=clone(history[n]);save(false);render()}
async function upload(input,type){const file=input.files[0];if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))return toast('Нужен PNG, JPG, WebP или GIF');toast(file.type==='image/gif'?'GIF сохраняется с анимацией':'Сжимаю изображение…');const data=await compressImage(file,type==='background'?1600:600);if(type==='background')project.background.custom=data;else if(type==='hammer')project.hitItem.image=data;else project.characters.push({id:'c'+Date.now(),name:file.name,kind:'normal',points:10,scale:1,image:data,emoji:'🎭'});save();render();toast('Изображение оптимизировано')}
function compressImage(file,maxSize){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{if(file.type==='image/gif')return resolve(r.result);const img=new Image();img.onload=()=>{const ratio=Math.min(1,maxSize/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.78))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function bindStageDrag(){document.querySelectorAll('.hole.edit').forEach(el=>el.onpointerdown=e=>{const i=+el.dataset.hole,stage=$('#stage');el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{const r=stage.getBoundingClientRect();project.holes[i].x=Math.max(4,Math.min(96,(ev.clientX-r.left)/r.width*100));project.holes[i].y=Math.max(12,Math.min(94,(ev.clientY-r.top)/r.height*100));el.style.left=project.holes[i].x+'%';el.style.top=project.holes[i].y+'%'};el.onpointerup=()=>{save();renderPreview()}})}
function bindHammerControl(){const hammer=document.querySelector('[data-hammer-control]'),stage=$('#stage');if(!hammer||!stage||!ui.testing)return;hammer.onpointerdown=e=>{e.preventDefault();ui.hammerHeld=true;hammer.classList.add('held');hammer.setPointerCapture(e.pointerId);const move=ev=>{const r=stage.getBoundingClientRect();ui.hammerCursor={x:Math.max(3,Math.min(97,(ev.clientX-r.left)/r.width*100)),y:Math.max(8,Math.min(97,(ev.clientY-r.top)/r.height*100))};hammer.style.left=ui.hammerCursor.x+'%';hammer.style.top=ui.hammerCursor.y+'%';const hitPadding=Math.max(42,r.width*.035),target=[...document.querySelectorAll('[data-hit]')].find(x=>{const b=x.getBoundingClientRect();return ev.clientX>b.left-hitPadding&&ev.clientX<b.right+hitPadding&&ev.clientY>b.top-hitPadding&&ev.clientY<b.bottom+hitPadding});if(target){ui.hammerHeld=false;hit(target.dataset.hit,ev)}};hammer.onpointermove=move;hammer.onpointerup=ev=>{if(!ui.hammerHeld)return;move(ev);ui.hammerHeld=false;hammer.classList.remove('held');renderPreview()}}}
function bindSelectionControl(){const box=document.querySelector('[data-selection]'),stage=$('#stage');if(!box||!stage)return;box.onpointerdown=e=>{e.preventDefault();const kind=box.dataset.selection,p=project.editorLayout[kind],resize=!!e.target.closest('[data-resize]'),r=stage.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,start={...p};box.setPointerCapture(e.pointerId);box.onpointermove=ev=>{if(resize){p.size=Math.max(6,Math.min(58,start.size+(ev.clientX-sx)/r.width*100));box.style.width=p.size+'%';if(kind==='hammer')project.hitItem.size=Math.round(p.size*5);if(kind==='hero')project.characters[0].scale=+(p.size/14).toFixed(2);if(kind==='danger')(project.characters.find(c=>c.kind==='danger')||project.characters[2]).scale=+(p.size/14).toFixed(2)}else{p.x=Math.max(3,Math.min(97,start.x+(ev.clientX-sx)/r.width*100));p.y=Math.max(5,Math.min(95,start.y+(ev.clientY-sy)/r.height*100));box.style.left=p.x+'%';box.style.top=p.y+'%'}};box.onpointerup=()=>{save();renderPreview()}}}

function startGame(){ui.testing=true;ui.screen='title';ui.gameState='TITLE';ui.score=0;ui.lives=project.game.lives;ui.time=project.game.duration;ui.active=[];ui.question=null;clearTimers();renderPreview()}
function stopGame(){clearTimers();ui.testing=false;ui.gameState='TITLE';ui.screen='game';ui.active=[];ui.question=null;renderPreview()}
function startPlaying(){clearTimers();unlockAudio();sound('spawn');ui.testing=true;ui.screen='game';ui.gameState='PLAYING';ui.score=0;ui.lives=project.game.lives;ui.time=project.game.duration;ui.active=[];countdown=setInterval(()=>{if(ui.gameState==='PLAYING'){ui.time--;if(ui.time<=0)finish();else if(!ui.hammerHeld)renderPreview()}},1000);scheduleSpawn();renderPreview()}
function scheduleSpawn(){if(!ui.testing||ui.gameState==='WIN'||ui.gameState==='LOSE')return;if(project.spawnSettings.mode==='timeline'){project.spawnTimeline.forEach(e=>setTimeout(()=>spawn(e.hole,e.character),e.time*1000));return}const tick=()=>{if(ui.gameState==='PLAYING')spawn();spawnTimer=setTimeout(tick,rand(project.spawnSettings.minInterval,project.spawnSettings.maxInterval))};tick()}
function spawn(hole=Math.floor(Math.random()*project.holes.length),char){if(ui.active.length>=project.spawnSettings.maxActive||ui.active.some(a=>a.hole===hole))return;const r=Math.random();char=char||(r<.12?'bomb':r<.25?'frog':'mole');const a={id:Date.now()+Math.random(),hole,char,hit:false};ui.active.push(a);sound('spawn');if(!ui.hammerHeld)renderPreview();setTimeout(()=>{ui.active=ui.active.filter(x=>x.id!==a.id);if(ui.gameState==='PLAYING'&&!ui.hammerHeld)renderPreview()},project.spawnSettings.visibleFor)}
function hit(id,e){const a=ui.active.find(x=>String(x.id)===String(id));if(!a||a.hit)return;a.hit=true;sound('hit');const c=project.characters.find(x=>x.id===a.char),h=project.holes[a.hole],questionAfter=c.kind==='normal'?project.questions[Math.floor(Math.random()*project.questions.length)]:null;ui.hammer={x:h.x,y:h.y};ui.fx={x:h.x,y:h.y,text:(c.points>0?'+':'')+c.points};ui.score=Math.max(0,ui.score+c.points);if(c.kind==='danger'){ui.lives--;sound('wrong')}renderPreview();setTimeout(()=>{ui.hammer=null;ui.fx=null;ui.active=ui.active.filter(x=>x.id!==a.id);if(ui.lives<=0)return finish(true);if(questionAfter){ui.question=questionAfter;ui.gameState='QUESTION'}renderPreview()},project.hitItem.duration)}
function selectAnswer(v){const q=ui.question;if(!q)return;if(q.type==='single')ui.selected=[v];else if(q.type==='multiple')ui.selected=ui.selected.includes(v)?ui.selected.filter(x=>x!==v):[...ui.selected,v];else if(q.type==='order')ui.selected=ui.selected.includes(v)?ui.selected.filter(x=>x!==v):[...ui.selected,v];renderPreview()}
function checkAnswer(){const q=ui.question;if(!q)return;let a=q.type==='input'?($('#answerInput')?.value||'').trim().toLowerCase():ui.selected;let ok=q.type==='input'?q.correct.some(x=>x.toLowerCase()===a):q.correct.length===a.length&&q.correct.every((x,i)=>q.type==='order'?x===a[i]:a.includes(x));if(ok)ui.score+=q.points;else ui.lives--;sound(ok?'correct':'wrong');ui.question=null;ui.selected=[];ui.screen=ok?'correct':'wrong';renderPreview();setTimeout(()=>{if(ui.lives<=0)finish(true);else if(ui.score>=project.game.targetScore)finish(false);else{ui.screen='game';ui.gameState='PLAYING';renderPreview()}},900)}
function finish(lose=false){clearTimers();sound(lose?'lose':'win');ui.gameState=lose?'LOSE':'WIN';ui.screen=lose?'lose':'win';ui.active=[];ui.question=null;renderPreview()}
let audioContext;
function unlockAudio(){try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume()}catch{}}
function sound(type){if(!project.sounds.enabled||project.sounds[type]===false)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime,notes={spawn:[520,.08],hit:[150,.12],correct:[740,.2],wrong:[110,.25],win:[880,.45],lose:[90,.45]},[hz,len]=notes[type]||notes.hit;o.type=type==='hit'?'square':'sine';o.frequency.setValueAtTime(hz,now);if(type==='correct'||type==='win')o.frequency.exponentialRampToValueAtTime(hz*1.6,now+len);g.gain.setValueAtTime(Math.max(.001,project.sounds.volume*.16),now);g.gain.exponentialRampToValueAtTime(.001,now+len);o.connect(g).connect(audioContext.destination);o.start(now);o.stop(now+len)}catch{}}
function clearTimers(){clearInterval(countdown);clearTimeout(spawnTimer)}const rand=(a,b)=>Math.round(a+Math.random()*(b-a));

function questionDialog(i){const q=i>=0?clone(project.questions[i]):{id:crypto.randomUUID(),type:'single',text:'Новый вопрос',options:['Вариант 1','Вариант 2'],correct:['Вариант 1'],points:20};$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog"><div class="dialog-head"><h2>${i>=0?'Редактировать':'Новое'} задание</h2><button class="mini" data-close>×</button></div><label class="field"><span>Тип задания</span><select id="qtype"><option value="input" ${q.type==='input'?'selected':''}>Ввод ответа</option><option value="single" ${q.type==='single'?'selected':''}>Один ответ</option><option value="multiple" ${q.type==='multiple'?'selected':''}>Несколько ответов</option><option value="order" ${q.type==='order'?'selected':''}>Порядок</option></select></label><label class="field"><span>Вопрос</span><textarea id="qtext">${esc(q.text)}</textarea></label><label class="field"><span>Варианты через новую строку</span><textarea id="qoptions">${esc(q.options.join('\n'))}</textarea></label><label class="field"><span>Правильные ответы через новую строку</span><textarea id="qcorrect">${esc(q.correct.join('\n'))}</textarea></label><label class="field"><span>Очки</span><input type="number" id="qpoints" value="${q.points}"></label><button class="btn primary" id="saveQ">Сохранить задание</button></div></div>`;document.querySelector('[data-close]').onclick=()=>$('#overlay').innerHTML='';$('#saveQ').onclick=()=>{q.type=$('#qtype').value;q.text=$('#qtext').value;q.options=$('#qoptions').value.split('\n').map(x=>x.trim()).filter(Boolean);q.correct=$('#qcorrect').value.split('\n').map(x=>x.trim()).filter(Boolean);q.points=+$('#qpoints').value;if(i>=0)project.questions[i]=q;else project.questions.push(q);$('#overlay').innerHTML='';save();render()}}
function projectDialog(){$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog"><div class="dialog-head"><h2>Проект</h2><button class="mini" data-close>×</button></div><div class="row"><button class="btn" id="newP">Новый проект</button><button class="btn" id="exportJ">Экспорт JSON</button><label class="btn" style="text-align:center">Импорт JSON<input hidden type="file" id="importJ" accept="application/json"></label></div></div></div>`;$('[data-close]').onclick=()=>$('#overlay').innerHTML='';$('#newP').onclick=()=>{project=clone(defaultProject);save();render()};$('#exportJ').onclick=()=>downloadBlob(JSON.stringify(project,null,2),'bei-krota-project.json','application/json');$('#importJ').onchange=e=>{const r=new FileReader;r.onload=()=>{try{project=JSON.parse(r.result);save();render()}catch{toast('Не удалось прочитать проект')}};r.readAsText(e.target.files[0])}}
function exportDialog(){const payload=btoa(unescape(encodeURIComponent(JSON.stringify(project)))),gameUrl=`${location.origin}${location.pathname}?mode=game#p=${payload}`,code=`<iframe src="${gameUrl}" frameborder="0" allow="autoplay; fullscreen" style="display:block;width:100%;height:100%;min-height:100%;border:0;margin:0;padding:0;overflow:hidden;"></iframe>`;$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog"><div class="dialog-head"><h2>${t('genially')}</h2><button class="mini" data-close>×</button></div><p class="label">Код скрыт и готов. Вставьте его в HTML-блок Genially и растяните блок на весь слайд.</p><div class="code-ready">✓ Код Genially подготовлен</div><div class="row" style="margin-top:12px"><button class="btn primary" id="copyCode">Копировать код</button><button class="btn" id="previewCode">Предпросмотр</button><button class="btn" id="downGame">${t('download')}</button></div></div></div>`;$('[data-close]').onclick=()=>$('#overlay').innerHTML='';$('#copyCode').onclick=()=>navigator.clipboard.writeText(code).then(()=>toast('Код Genially скопирован'));$('#previewCode').onclick=()=>window.open(gameUrl,'_blank');$('#downGame').onclick=downloadHTML}
function resumeDialog(){if(!savedRaw||embedded)return;$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog resume-dialog"><h2>Найдено автосохранение</h2><p>Продолжить работу с последними изменениями?</p><div class="row"><button class="btn primary" id="continueSaved">Продолжить дальше</button><button class="btn pink" id="deleteSaved">Удалить</button></div></div></div>`;$('#continueSaved').onclick=()=>{$('#overlay').innerHTML='';toast('Последние изменения восстановлены')};$('#deleteSaved').onclick=()=>{localStorage.removeItem('whackProject');location.reload()}}
function generateHTML(){const data=JSON.stringify(project).replace(/</g,'\\u003c');return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(project.meta.title)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#080c18;color:#fff;font-family:system-ui;display:grid;place-items:center;min-height:100vh}.game{position:relative;width:min(100vw,1100px);aspect-ratio:16/9;overflow:hidden;background:linear-gradient(#7ed0ea 0 35%,#71b94e 35% 44%,#8d552d 44%);${project.background.custom?`background-image:url(${project.background.custom});background-size:${project.background.fit};background-position:center`:''}}.hud{position:absolute;z-index:8;inset:15px 15px auto;display:flex;justify-content:center;gap:10px}.pill{background:#10162ddd;border:1px solid #fff3;border-radius:12px;padding:8px 14px;font-weight:800}.hole{position:absolute;transform:translate(-50%,-50%);width:16%;aspect-ratio:1.9;border-radius:50%;background:radial-gradient(ellipse,#140d08 15%,#342116 50%,#936945 54%,#59402c 68%,transparent 70%)}.char{position:absolute;z-index:3;transform:translate(-50%,-72%);font-size:clamp(42px,8vw,95px);cursor:pointer;user-select:none;filter:drop-shadow(0 8px 5px #0007);animation:up .25s}@keyframes up{from{transform:translate(-50%,-20%);opacity:0}}.cover,.modal{position:absolute;inset:0;z-index:12;display:grid;place-items:center;background:#080c19d9;backdrop-filter:blur(5px)}.card{width:min(76%,620px);padding:34px;text-align:center;background:#10182e;border:2px solid ${project.design.accent};border-radius:${project.design.radius}px;box-shadow:0 0 35px ${project.design.accent}66}.card h1{font-size:clamp(28px,5vw,55px);margin:5px}.card p{color:#c8cee2}.go,.answer{border:0;border-radius:11px;padding:13px 22px;color:#fff;background:${project.design.button};font-size:17px;font-weight:800;cursor:pointer}.answers{display:grid;grid-template-columns:1fr 1fr;gap:10px}.answer{background:#202947;border:1px solid #4c587e}.answer.sel{background:${project.design.accent}}input{width:100%;padding:14px;background:#091020;color:#fff;border:1px solid #4c587e;border-radius:10px}.fx{position:absolute;z-index:20;font-size:30px;font-weight:900;color:#ffe066;animation:fly .7s forwards}@keyframes fly{to{transform:translateY(-60px);opacity:0}}@media(max-width:650px){.game{aspect-ratio:9/16}.answers{grid-template-columns:1fr}.card{width:90%;padding:22px}}
</style></head><body><div class="game" id="game"></div><script>
const P=${data},G=document.getElementById('game');let score=0,lives=P.game.lives,time=P.game.duration,active=[],question=null,selected=[],clock,spawner;
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function title(){G.innerHTML='<div class="cover"><div class="card"><div style="font-size:65px">🦫 🔨</div><h1>'+E(P.meta.title)+'</h1><p>'+E(P.screens.subtitle)+'</p><p>'+E(P.screens.instruction)+'</p><button class="go" id="go">'+E(P.screens.playButton)+'</button></div></div>';document.getElementById('go').onclick=start}
function hud(){return '<div class="hud">'+(P.game.showTimer?'<div class="pill">⏱ '+String(Math.floor(time/60)).padStart(2,'0')+':'+String(time%60).padStart(2,'0')+'</div>':'')+(P.game.showScore?'<div class="pill">⭐ '+score+'</div>':'')+(P.game.showLives?'<div class="pill">❤️ '+lives+'</div>':'')+'</div>'}
function draw(){G.innerHTML=hud()+P.holes.map((h,i)=>'<div class="hole" style="left:'+h.x+'%;top:'+h.y+'%"></div>').join('')+active.map(a=>{const h=P.holes[a.hole],c=P.characters.find(x=>x.id===a.char);return '<div class="char" data-id="'+a.id+'" style="left:'+h.x+'%;top:'+h.y+'%">'+(c.image?'<img src="'+c.image+'" style="width:12vw;max-width:110px">':c.emoji)+'</div>'}).join('')+(question?qhtml(question):'');G.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>hit(x.dataset.id));bindQuestion()}
function start(){score=0;lives=P.game.lives;time=P.game.duration;active=[];clearInterval(clock);clearTimeout(spawner);clock=setInterval(()=>{time--;if(time<=0)end(false);else draw()},1000);spawnLoop();draw()}
function spawnLoop(){const add=()=>{if(active.length<P.spawnSettings.maxActive){let hole=Math.floor(Math.random()*P.holes.length);if(!active.some(x=>x.hole===hole)){let r=Math.random(),char=r<.12?'bomb':r<.25?'frog':'mole',a={id:Date.now()+Math.random(),hole,char};active.push(a);draw();setTimeout(()=>{active=active.filter(x=>x.id!==a.id);draw()},P.spawnSettings.visibleFor)}}spawner=setTimeout(add,P.spawnSettings.minInterval+Math.random()*(P.spawnSettings.maxInterval-P.spawnSettings.minInterval))};add()}
function hit(id){const a=active.find(x=>String(x.id)===String(id));if(!a)return;const c=P.characters.find(x=>x.id===a.char);active=active.filter(x=>x!==a);score=Math.max(0,score+c.points);if(c.kind==='danger'){lives--;if(lives<=0)return end(true)}else if(c.kind==='normal')question=P.questions[Math.floor(Math.random()*P.questions.length)];draw()}
function qhtml(q){let body=q.type==='input'?'<input id="inp" placeholder="Введите ответ">':'<div class="answers">'+q.options.map(o=>'<button class="answer" data-a="'+E(o)+'">'+E(o)+'</button>').join('')+'</div>';return '<div class="modal"><div class="card"><h3>❓ ЗАДАНИЕ</h3><h2>'+E(q.text)+'</h2>'+body+'<button class="go" id="check" style="margin-top:14px">Проверить</button></div></div>'}
function bindQuestion(){if(!question)return;G.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(question.type==='single')selected=[b.dataset.a];else selected.includes(b.dataset.a)?selected=selected.filter(x=>x!==b.dataset.a):selected.push(b.dataset.a);G.querySelectorAll('[data-a]').forEach(x=>x.classList.toggle('sel',selected.includes(x.dataset.a))) });const c=document.getElementById('check');if(c)c.onclick=check}
function check(){let ok;if(question.type==='input'){let v=document.getElementById('inp').value.trim().toLowerCase();ok=question.correct.some(x=>x.toLowerCase()===v)}else ok=question.correct.length===selected.length&&question.correct.every(x=>selected.includes(x));if(ok)score+=question.points;else lives--;question=null;selected=[];if(lives<=0)end(true);else if(score>=P.game.targetScore)end(false);else draw()}
function end(lose){clearInterval(clock);clearTimeout(spawner);G.innerHTML='<div class="cover"><div class="card"><div style="font-size:65px">'+(lose?'💔':'🏆')+'</div><h1>'+E(lose?P.screens.loseTitle:P.screens.winTitle)+'</h1><p>Результат: <b>'+score+'</b> очков</p><button class="go" id="again">Играть ещё раз</button></div></div>';document.getElementById('again').onclick=start}title();
<\/script></body></html>`}
function downloadHTML(){downloadBlob(generateHTML(),'bei-krota-game.html','text/html')}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),1800)}

render();
resumeDialog();
if(embedded)startGame();
