import {defaultProject,holeLayouts} from './defaults.js';
import {translations,languageNames,phraseTranslations} from './i18n.js';

const clone=o=>JSON.parse(JSON.stringify(o));
let project=(()=>{try{return {...clone(defaultProject),...JSON.parse(localStorage.getItem('whackProject'))}}catch{return clone(defaultProject)}})();
project.design={...clone(defaultProject.design),...(project.design||{}),screens:{...clone(defaultProject.design.screens),...(project.design?.screens||{})}};
project.sounds={...clone(defaultProject.sounds),...(project.sounds||{})};
let ui={tab:'design',screen:'title',testing:false,gameState:'TITLE',score:0,lives:project.game.lives,time:project.game.duration,active:[],question:null,selected:[],fx:null,hammer:null,save:'Сохранено'};
let history=[clone(project)],historyIndex=0,spawnTimer,countdown;
const $=s=>document.querySelector(s);

const t=k=>(translations[project.meta.language]||translations.ru)[k]||translations.ru[k]||k;
const tabs=[['design','🎨','design'],['game','🎮','game'],['characters','🦫','characters'],['hammer','🔨','hammer'],['spawn','⏱','spawn'],['questions','❓','questions'],['screens','🖥','screens'],['settings','⚙','settings']];
const backgrounds={garden:['Сад','#79b84d'],space:['Космос','#31205e'],board:['Доска','#285148'],desert:['Пустыня','#dca749']};

function save(push=true){ui.save='Сохранение…';if(push){history=history.slice(0,historyIndex+1);history.push(clone(project));historyIndex=history.length-1}renderTop();clearTimeout(save.t);save.t=setTimeout(()=>{localStorage.setItem('whackProject',JSON.stringify(project));ui.save='Сохранено';renderTop()},450)}
function set(path,value,push=true){let o=project;const keys=path.split('.');keys.slice(0,-1).forEach(k=>o=o[k]);o[keys.at(-1)]=value;save(push);render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function field(label,path,type='text',extra=''){const value=path.split('.').reduce((o,k)=>o[k],project);return `<label class="field"><span>${label}</span><input type="${type}" data-path="${path}" value="${esc(value)}" ${extra}></label>`}
function toggle(label,path){const v=path.split('.').reduce((o,k)=>o[k],project);return `<div class="toggle-row"><span>${label}</span><button class="toggle ${v?'on':''}" data-toggle="${path}"></button></div>`}
function card(title,body){return `<section class="card"><div class="card-head">${title}</div><div class="card-body">${body}</div></section>`}

function render(){document.querySelector('#app').innerHTML=`<div class="app"><header class="topbar" id="top"></header><main class="workspace"><aside class="sidebar"><nav class="tabs">${tabs.map(x=>`<button class="tab ${ui.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]} ${t(x[2])}</button>`).join('')}</nav><div class="panel" id="panel"></div><footer class="copyright">${t('footer')}</footer></aside><section class="preview-pane" id="preview"></section></main></div><div id="overlay"></div>`;renderTop();renderPanel();renderPreview();bind()}
function renderTop(){const el=$('#top');if(!el)return;el.innerHTML=`<div class="brand"><div class="logo">🔨</div><div><strong>${t('brand')}</strong><small>${t('editor')}</small></div></div><label class="language-select">🌐 <select id="language">${Object.entries(languageNames).map(([k,v])=>`<option value="${k}" ${project.meta.language===k?'selected':''}>${v}</option>`).join('')}</select></label><span class="save">● ${ui.save==='Сохранение…'?t('saving'):t('saved')}</span><div class="top-actions"><button class="btn icon" data-action="undo" title="Undo">↶</button><button class="btn icon" data-action="redo" title="Redo">↷</button><button class="btn" data-action="project"><span class="hide-sm">${t('project')}</span> ▾</button><button class="btn" data-action="download">${t('download')}</button><button class="btn pink" data-action="genially">${t('genially')}</button></div>`}

function renderPanel(){let html='';
 if(ui.tab==='design') html=`<div class="eyebrow">Оформление</div><h2>Вид игры</h2>${card('Готовая тема',`<div class="swatches">${Object.entries(backgrounds).map(([k,v])=>`<button class="swatch ${project.background.preset===k?'active':''}" data-bg="${k}" style="background:${v[1]}">${v[0]}</button>`).join('')}</div>`)}${card('Цвета и форма',`${field('Акцентный цвет','design.accent','color')} ${field('Цвет кнопок','design.button','color')} ${field('Скругление','design.radius','range','min="4" max="40" class="range"')}`)}${card('Свой фон',`<label class="upload">＋ Загрузить PNG, JPG, WebP или GIF<input hidden type="file" data-upload="background" accept="image/png,image/jpeg,image/webp,image/gif"></label>`)}`;
 if(ui.tab==='game') html=`<div class="eyebrow">Игровое поле</div><h2>Норы и фон</h2>${card('Количество нор',`<div class="row"><select id="holes">${[3,4,6,8,9,12].map(n=>`<option ${project.holes.length===n?'selected':''}>${n}</option>`).join('')}</select><button class="btn" data-action="add-hole">＋ Место</button></div><p class="label" style="margin-top:12px">Перетаскивайте норы прямо в предпросмотре.</p>`)}${card('Масштаб фона',`<label class="field"><span>Режим</span><select data-path="background.fit"><option value="cover">Заполнить</option><option value="contain">Вместить</option><option value="100% 100%">Растянуть</option></select></label>`)}`;
 if(ui.tab==='characters') html=`<div class="eyebrow">Анимированная библиотека</div><h2>Персонажи и препятствия</h2>${card('Выберите героя',`<div class="asset-grid">${[['🐹','Крот'],['🐸','Лягушка'],['👾','Монстр'],['🤖','Робот'],['👻','Привидение'],['🐧','Пингвин']].map(x=>`<button class="asset animated-asset" data-library-char="${x[0]}" data-name="${x[1]}"><span class="emoji">${x[0]}</span><small>${x[1]}</small></button>`).join('')}</div>`)}${card('Препятствия',`<div class="asset-grid">${[['💣','Бомба'],['🧨','Динамит'],['🕷️','Паук'],['⚡','Молния'],['🌵','Кактус'],['🪨','Камень']].map(x=>`<button class="asset animated-asset danger-asset" data-library-danger="${x[0]}" data-name="${x[1]}"><span class="emoji">${x[0]}</span><small>${x[1]}</small></button>`).join('')}</div>`)}${project.characters.map((c,i)=>card(`${c.emoji} ${esc(c.name)}`,`${field('Название',`characters.${i}.name`)}<div class="row">${field('Очки',`characters.${i}.points`,'number')}${field('Масштаб',`characters.${i}.scale`,'range','min="0.6" max="1.5" step="0.1"')}</div><label class="field"><span>Тип</span><select data-path="characters.${i}.kind"><option value="normal" ${c.kind==='normal'?'selected':''}>Обычный</option><option value="bonus" ${c.kind==='bonus'?'selected':''}>Бонус</option><option value="danger" ${c.kind==='danger'?'selected':''}>Опасный</option></select></label>`)).join('')}${card('Своя GIF-анимация',`<label class="upload">＋ Загрузить PNG, WebP, GIF или JPG<input hidden type="file" data-upload="character" accept="image/png,image/jpeg,image/webp,image/gif"></label><label class="field" style="margin-top:12px"><span>Или вставьте прямую ссылку на GIF</span><input id="gifUrl" placeholder="https://…/animation.gif"></label><button class="btn" data-action="add-gif-url">Добавить GIF</button><div class="giphy-credit">GIF library ready · поддержка GIPHY URL</div>`)}`;
 if(ui.tab==='hammer') html=`<div class="eyebrow">Инструмент</div><h2>Предмет удара</h2>${card('Выберите предмет',`<div class="asset-grid">${[['🔨','Молоток'],['🪄','Палочка'],['👟','Тапок'],['📕','Книга'],['⭐','Звезда'],['👊','Перчатка']].map(x=>`<button class="asset ${project.hitItem.emoji===x[0]?'active':''}" data-hammer="${x[0]}" data-name="${x[1]}"><span class="emoji">${x[0]}</span><small>${x[1]}</small></button>`).join('')}</div>`)}${card('Анимация',`${field('Размер','hitItem.size','range','min="35" max="120" class="range"')}${field('Длительность, мс','hitItem.duration','range','min="120" max="700" class="range"')}`)}`;
 if(ui.tab==='spawn') html=`<div class="eyebrow">Динамика</div><h2>Появления</h2>${card('Режим',`<div class="row"><button class="btn ${project.spawnSettings.mode==='random'?'primary':''}" data-mode="random">Случайно</button><button class="btn ${project.spawnSettings.mode==='timeline'?'primary':''}" data-mode="timeline">Сценарий</button></div>`)}${project.spawnSettings.mode==='random'?card('Случайные появления',`${field('Минимальный интервал, мс','spawnSettings.minInterval','number')}${field('Максимальный интервал, мс','spawnSettings.maxInterval','number')}${field('Видимость, мс','spawnSettings.visibleFor','number')}${field('Одновременно','spawnSettings.maxActive','number')}`):card('Сценарий',`${project.spawnTimeline.map((e,i)=>`<div class="timeline-row"><input style="width:56px" type="number" value="${e.time}" data-timeline="${i}:time"><span>сек →</span><select data-timeline="${i}:character">${project.characters.map(c=>`<option value="${c.id}" ${e.character===c.id?'selected':''}>${c.emoji}</option>`).join('')}</select><input style="width:50px" type="number" value="${e.hole+1}" data-timeline="${i}:hole"><button class="mini" data-del-timeline="${i}">×</button></div>`).join('')}<button class="btn" data-action="add-spawn">＋ Добавить появление</button>`)}`;
 if(ui.tab==='questions') html=questionsPanel();
 if(ui.tab==='screens') html=`<div class="eyebrow">Тексты и оформление</div><h2>Все экраны игры</h2>${card('Титульный экран',`${field('Название игры','meta.title')}${field('Подзаголовок','screens.subtitle')}<label class="field"><span>Инструкция</span><textarea data-path="screens.instruction">${esc(project.screens.instruction)}</textarea></label>${field('Название кнопки','screens.playButton')}${appearanceFields('title')}`)}${card('Окно задания',appearanceFields('question'))}${card('Экран победы',`${field('Заголовок','screens.winTitle')}${appearanceFields('win')}`)}${card('Экран поражения',`${field('Заголовок','screens.loseTitle')}${appearanceFields('lose')}`)}`;
 if(ui.tab==='settings') html=`<div class="eyebrow">Правила</div><h2>Параметры игры</h2>${card('Основное',`${field('Время игры, сек','game.duration','number')}${field('Количество жизней','game.lives','number')}${field('Очков для победы','game.targetScore','number')}`)}${card('Игровой интерфейс',`${toggle('Показывать таймер','game.showTimer')}${toggle('Показывать очки','game.showScore')}${toggle('Показывать жизни','game.showLives')}${toggle('Пауза во время вопроса','game.pauseDuringQuestion')}`)}${card('Звуковые эффекты',`${toggle('Включить звук','sounds.enabled')}${field('Громкость','sounds.volume','range','min="0" max="1" step="0.05" class="range"')}${toggle('Появление','sounds.spawn')}${toggle('Удар','sounds.hit')}${toggle('Правильный ответ','sounds.correct')}${toggle('Ошибка','sounds.wrong')}${toggle('Победа','sounds.win')}${toggle('Поражение','sounds.lose')}<button class="btn" data-action="sound-test">▶ Проверить звук</button>`)}`;
 $('#panel').innerHTML=html;localizeUI($('#panel'));
}
function appearanceFields(name){return `<div class="style-grid"><label class="field"><span>Шрифт</span><select data-path="design.screens.${name}.font"><option>Manrope</option><option>Arial</option><option>Georgia</option><option>Trebuchet MS</option><option>Courier New</option></select></label>${field('Размер заголовка',`design.screens.${name}.titleSize`,'range','min="20" max="80" class="range"')}${field('Цвет текста',`design.screens.${name}.text`,'color')}${field('Фон окна',`design.screens.${name}.background`,'color')}${field('Цвет рамки',`design.screens.${name}.border`,'color')}${field('Свечение окна',`design.screens.${name}.glow`,'color')}${field('Цвет кнопки',`design.screens.${name}.button`,'color')}${field('Текст кнопки',`design.screens.${name}.buttonText`,'color')}${field('Свечение кнопки',`design.screens.${name}.buttonGlow`,'color')}</div>`}
function localizeUI(root){if(project.meta.language==='ru'||!root)return;const col=project.meta.language==='en'?0:1,w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{const raw=n.nodeValue,trim=raw.trim(),v=phraseTranslations[trim]?.[col];if(v)n.nodeValue=raw.replace(trim,v)})}
function questionsPanel(){return `<div class="eyebrow">Учебный контент</div><h2>Банк заданий</h2>${project.questions.map((q,i)=>`<div class="question-item"><span>${q.type==='input'?'⌨️':q.type==='multiple'?'☑️':q.type==='order'?'↕️':'🔘'}</span><div class="grow"><strong>Задание ${i+1}</strong><small>${esc(q.text)}</small></div><button class="mini" data-edit-q="${i}">✎</button><button class="mini" data-copy-q="${i}">⧉</button><button class="mini" data-del-q="${i}">×</button></div>`).join('')}<button class="btn primary" data-action="add-question">＋ Добавить задание</button>`}

function renderPreview(){const screens=[['game','🎮','play'],['title','🏠','title'],['question','❓','question'],['correct','✅','correct'],['wrong','❌','wrong'],['win','🏆','win'],['lose','💔','lose']];$('#preview').innerHTML=`<div class="preview-head"><div><div class="eyebrow">👁 ${t('preview')}</div><h1>${t('student')}</h1></div><div class="preview-actions"><button class="btn green">${ui.testing?t('testing'):t('edit')}</button><button class="btn primary" data-action="test">${ui.testing?'■ '+t('stop'):'▶ '+t('test')}</button></div></div><div class="screens">${screens.map(s=>`<button class="screen-btn ${ui.screen===s[0]?'active':''}" data-screen="${s[0]}">${s[1]} ${t(s[2])}</button>`).join('')}</div><div class="stage-shell"><div class="stage bg-${project.background.preset}" id="stage" style="${project.background.custom?`background-image:url(${project.background.custom});background-size:${project.background.fit};background-position:center`:''};--accent:${project.design.accent};border-radius:${project.design.radius/2}px">${stageHTML()}</div></div><div class="hint">Live preview · Drag holes to change positions</div>`;localizeUI($('#preview'));bindStageDrag()}
function stageHTML(){if(ui.screen==='title'||(ui.testing&&ui.gameState==='TITLE'))return titleHTML();if(['win','lose'].includes(ui.screen)||['WIN','LOSE'].includes(ui.gameState))return endHTML(ui.screen==='lose'||ui.gameState==='LOSE');if(ui.screen==='question'&&!ui.question)ui.question=project.questions[0];return `<div class="game-hud">${project.game.showTimer?`<div class="hud-pill">⏱ ${fmt(ui.testing?ui.time:23)}</div>`:''}${project.game.showScore?`<div class="hud-pill">⭐ ${ui.testing?ui.score:40}</div>`:''}${project.game.showLives?`<div class="hud-pill">❤️ ${ui.testing?ui.lives:project.game.lives}</div>`:''}</div>${project.holes.map((h,i)=>`<div class="hole ${!ui.testing?'edit':''}" data-hole="${i}" style="left:${h.x}%;top:${h.y}%"></div>${moleAt(i,h)}`).join('')}${ui.question||ui.screen==='question'?questionHTML():''}${ui.screen==='correct'?feedbackHTML(true):''}${ui.screen==='wrong'?feedbackHTML(false):''}${ui.fx?`<div class="hit-fx" style="left:${ui.fx.x}%;top:${ui.fx.y}%">${ui.fx.text}</div>`:''}${ui.hammer?`<div class="hammer" style="left:${ui.hammer.x}%;top:${ui.hammer.y}%;font-size:${project.hitItem.size}px">${project.hitItem.emoji}</div>`:''}`}
function moleAt(i,h){const a=ui.active.find(x=>x.hole===i);if(!a&&!ui.testing)return i===1?`<div class="mole-wrap" style="left:${h.x}%;top:${h.y}%"><div class="mole up" data-hit="demo">${project.characters[0].emoji}</div></div>`:'';if(!a)return'';const c=project.characters.find(x=>x.id===a.char);return `<div class="mole-wrap" style="left:${h.x}%;top:${h.y}%;transform:translate(-50%,-66%) scale(${c.scale})"><div class="mole up ${a.hit?'hit':''}" data-hit="${a.id}">${c.image?`<img src="${c.image}" style="width:100%">`:c.emoji}</div></div>`}
function boxStyle(name){const s=project.design.screens?.[name]||defaultProject.design.screens[name];return `font-family:${s.font};color:${s.text};background:${s.background};border-color:${s.border};box-shadow:0 0 42px ${s.glow}88`}
function headingStyle(name){const s=project.design.screens?.[name]||defaultProject.design.screens[name];return `font-size:${s.titleSize}px;color:${s.text}`}
function buttonStyle(name){const s=project.design.screens?.[name]||defaultProject.design.screens[name];return `background:${s.button};color:${s.buttonText};box-shadow:0 8px 22px ${s.buttonGlow}88`}
function titleHTML(){return `<div class="title-screen"><div class="hero-card" style="${boxStyle('title')}"><div class="mascot-pop">🦫</div><h2 style="${headingStyle('title')}">${esc(project.meta.title)}</h2><p>${esc(project.screens.subtitle)}</p><p style="font-size:12px">${esc(project.screens.instruction)}</p><button class="big-btn" style="${buttonStyle('title')}" data-action="play">${esc(project.screens.playButton)}</button></div></div>`}
function endHTML(lose=false){const n=lose?'lose':'win';return `<div class="end-screen"><div class="hero-card" style="${boxStyle(n)}"><div style="font-size:52px">${lose?'💔':'🏆'}</div><h2 style="${headingStyle(n)}">${esc(lose?project.screens.loseTitle:project.screens.winTitle)}</h2><p>${t('result')}: <strong>${ui.score}</strong> ${t('points')}</p><button class="big-btn" style="${buttonStyle(n)}" data-action="play">${t('again')}</button></div></div>`}
function questionHTML(){const q=ui.question||project.questions[0];if(!q)return'';const input=q.type==='input'?`<input class="question-input" id="answerInput" placeholder="${t('answerPlaceholder')}">`:`<div class="answers">${q.options.map(o=>`<button class="answer ${ui.selected.includes(o)?'selected':''}" data-answer="${esc(o)}">${q.type==='order'&&ui.selected.includes(o)?`${ui.selected.indexOf(o)+1}. `:''}${esc(o)}</button>`).join('')}</div>`;return `<div class="question-modal"><div class="question-card" style="${boxStyle('question')}"><h3>❓ ${t('task')}</h3><h2 style="${headingStyle('question')}">${esc(q.text)}</h2>${input}<button class="btn primary" style="margin-top:14px;width:100%;${buttonStyle('question')}" data-action="check">${t('check')}</button></div></div>`}
function feedbackHTML(ok){return `<div class="question-modal"><div class="question-card" style="text-align:center"><div style="font-size:52px">${ok?'✅':'❌'}</div><h2>${ok?'Правильно!':'Попробуй ещё раз'}</h2><p>${ok?'+20 очков':'Будь внимательнее'}</p></div></div>`}
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

 function bind(){document.onclick=e=>{const t=e.target.closest('button,[data-upload]');if(!t)return;if(t.dataset.tab){ui.tab=t.dataset.tab;renderPanel();bind()}if(t.dataset.screen){ui.screen=t.dataset.screen;ui.question=null;renderPreview()}if(t.dataset.bg)set('background.preset',t.dataset.bg);if(t.dataset.libraryChar){project.characters[0].emoji=t.dataset.libraryChar;project.characters[0].name=t.dataset.name;delete project.characters[0].image;save();render()}if(t.dataset.libraryDanger){const d=project.characters.find(c=>c.kind==='danger');d.emoji=t.dataset.libraryDanger;d.name=t.dataset.name;delete d.image;save();render()}if(t.dataset.hammer){project.hitItem.emoji=t.dataset.hammer;project.hitItem.name=t.dataset.name;save();render()}if(t.dataset.mode)set('spawnSettings.mode',t.dataset.mode);if(t.dataset.toggle){const p=t.dataset.toggle,v=p.split('.').reduce((o,k)=>o[k],project);set(p,!v)}if(t.dataset.answer)selectAnswer(t.dataset.answer);if(t.dataset.editQ)questionDialog(+t.dataset.editQ);if(t.dataset.copyQ){project.questions.splice(+t.dataset.copyQ+1,0,{...clone(project.questions[+t.dataset.copyQ]),id:crypto.randomUUID()});save();render()}if(t.dataset.delQ){project.questions.splice(+t.dataset.delQ,1);save();render()}if(t.dataset.delTimeline){project.spawnTimeline.splice(+t.dataset.delTimeline,1);save();render()}if(t.dataset.action)action(t.dataset.action)};
 document.oninput=e=>{const p=e.target.dataset.path;if(p){let v=e.target.type==='number'||e.target.type==='range'?+e.target.value:e.target.value;let o=project,ks=p.split('.');ks.slice(0,-1).forEach(k=>o=o[k]);o[ks.at(-1)]=v;save(false);renderPreview()}if(e.target.id==='holes'){project.holes=clone(holeLayouts[e.target.value]);save();render()}};
 document.onchange=e=>{if(e.target.id==='language'){project.meta.language=e.target.value;save();render();return}if(e.target.dataset.path)set(e.target.dataset.path,e.target.type==='number'?+e.target.value:e.target.value);if(e.target.dataset.upload)upload(e.target,e.target.dataset.upload);if(e.target.dataset.timeline){const [i,k]=e.target.dataset.timeline.split(':');project.spawnTimeline[i][k]=k==='character'?e.target.value:+e.target.value-(k==='hole'?1:0);save();render()}};
 document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1)}};
}
function action(a){if(a==='test')ui.testing?stopGame():startGame();if(a==='play')startPlaying();if(a==='check')checkAnswer();if(a==='undo')undo(-1);if(a==='redo')undo(1);if(a==='genially')exportDialog();if(a==='download')downloadHTML();if(a==='project')projectDialog();if(a==='sound-test')sound('correct');if(a==='add-gif-url'){const url=$('#gifUrl')?.value.trim();if(!/^https:\/\/.+\.(gif|webp)(\?.*)?$/i.test(url||''))return toast('Укажите прямую HTTPS-ссылку на GIF');project.characters.push({id:'gif'+Date.now(),name:'GIF персонаж',kind:'normal',points:10,scale:1,image:url,emoji:'🎭'});save();render()}if(a==='add-hole'){project.holes.push({x:50,y:50});save();render()}if(a==='add-question')questionDialog(-1);if(a==='add-spawn'){project.spawnTimeline.push({time:10,character:'mole',hole:0});save();render()}}
function undo(dir){const n=historyIndex+dir;if(n<0||n>=history.length)return;historyIndex=n;project=clone(history[n]);save(false);render()}
function upload(input,type){const file=input.files[0];if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))return toast('Нужен PNG, JPG, WebP или GIF');const r=new FileReader;r.onload=()=>{if(type==='background')project.background.custom=r.result;else project.characters.push({id:'c'+Date.now(),name:file.name,kind:'normal',points:10,scale:1,image:r.result,emoji:'🎭'});save();render()};r.readAsDataURL(file)}
function bindStageDrag(){document.querySelectorAll('.hole.edit').forEach(el=>el.onpointerdown=e=>{const i=+el.dataset.hole,stage=$('#stage');el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{const r=stage.getBoundingClientRect();project.holes[i].x=Math.max(4,Math.min(96,(ev.clientX-r.left)/r.width*100));project.holes[i].y=Math.max(12,Math.min(94,(ev.clientY-r.top)/r.height*100));el.style.left=project.holes[i].x+'%';el.style.top=project.holes[i].y+'%'};el.onpointerup=()=>{save();renderPreview()}})}

function startGame(){ui.testing=true;ui.screen='title';ui.gameState='TITLE';ui.score=0;ui.lives=project.game.lives;ui.time=project.game.duration;ui.active=[];ui.question=null;clearTimers();renderPreview()}
function stopGame(){clearTimers();ui.testing=false;ui.gameState='TITLE';ui.screen='game';ui.active=[];ui.question=null;renderPreview()}
function startPlaying(){clearTimers();ui.testing=true;ui.screen='game';ui.gameState='PLAYING';ui.score=0;ui.lives=project.game.lives;ui.time=project.game.duration;ui.active=[];countdown=setInterval(()=>{if(ui.gameState==='PLAYING'){ui.time--;if(ui.time<=0)finish();else renderPreview()}},1000);scheduleSpawn();renderPreview()}
function scheduleSpawn(){if(!ui.testing||ui.gameState==='WIN'||ui.gameState==='LOSE')return;if(project.spawnSettings.mode==='timeline'){project.spawnTimeline.forEach(e=>setTimeout(()=>spawn(e.hole,e.character),e.time*1000));return}const tick=()=>{if(ui.gameState==='PLAYING')spawn();spawnTimer=setTimeout(tick,rand(project.spawnSettings.minInterval,project.spawnSettings.maxInterval))};tick()}
function spawn(hole=Math.floor(Math.random()*project.holes.length),char){if(ui.active.length>=project.spawnSettings.maxActive||ui.active.some(a=>a.hole===hole))return;const r=Math.random();char=char||(r<.12?'bomb':r<.25?'frog':'mole');const a={id:Date.now()+Math.random(),hole,char,hit:false};ui.active.push(a);sound('spawn');renderPreview();setTimeout(()=>{ui.active=ui.active.filter(x=>x.id!==a.id);if(ui.gameState==='PLAYING')renderPreview()},project.spawnSettings.visibleFor)}
function hit(id,e){const a=ui.active.find(x=>String(x.id)===String(id));if(!a||a.hit)return;a.hit=true;sound('hit');const c=project.characters.find(x=>x.id===a.char),h=project.holes[a.hole];ui.hammer={x:h.x,y:h.y};ui.fx={x:h.x,y:h.y,text:(c.points>0?'+':'')+c.points};ui.score=Math.max(0,ui.score+c.points);if(c.kind==='danger'){ui.lives--;sound('wrong');if(ui.lives<=0){finish(true);return}}else if(c.kind==='normal'){ui.question=project.questions[Math.floor(Math.random()*project.questions.length)];ui.gameState='QUESTION'}setTimeout(()=>{ui.hammer=null;ui.fx=null;ui.active=ui.active.filter(x=>x.id!==a.id);renderPreview()},500);renderPreview()}
function selectAnswer(v){const q=ui.question;if(!q)return;if(q.type==='single')ui.selected=[v];else if(q.type==='multiple')ui.selected=ui.selected.includes(v)?ui.selected.filter(x=>x!==v):[...ui.selected,v];else if(q.type==='order')ui.selected=ui.selected.includes(v)?ui.selected.filter(x=>x!==v):[...ui.selected,v];renderPreview()}
function checkAnswer(){const q=ui.question;if(!q)return;let a=q.type==='input'?($('#answerInput')?.value||'').trim().toLowerCase():ui.selected;let ok=q.type==='input'?q.correct.some(x=>x.toLowerCase()===a):q.correct.length===a.length&&q.correct.every((x,i)=>q.type==='order'?x===a[i]:a.includes(x));if(ok)ui.score+=q.points;else ui.lives--;sound(ok?'correct':'wrong');ui.question=null;ui.selected=[];ui.screen=ok?'correct':'wrong';renderPreview();setTimeout(()=>{if(ui.lives<=0)finish(true);else if(ui.score>=project.game.targetScore)finish(false);else{ui.screen='game';ui.gameState='PLAYING';renderPreview()}},900)}
function finish(lose=false){clearTimers();sound(lose?'lose':'win');ui.gameState=lose?'LOSE':'WIN';ui.screen=lose?'lose':'win';ui.active=[];ui.question=null;renderPreview()}
let audioContext;
function sound(type){if(!project.sounds.enabled||project.sounds[type]===false)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime,notes={spawn:[520,.08],hit:[150,.12],correct:[740,.2],wrong:[110,.25],win:[880,.45],lose:[90,.45]},[hz,len]=notes[type]||notes.hit;o.type=type==='hit'?'square':'sine';o.frequency.setValueAtTime(hz,now);if(type==='correct'||type==='win')o.frequency.exponentialRampToValueAtTime(hz*1.6,now+len);g.gain.setValueAtTime(Math.max(.001,project.sounds.volume*.16),now);g.gain.exponentialRampToValueAtTime(.001,now+len);o.connect(g).connect(audioContext.destination);o.start(now);o.stop(now+len)}catch{}}
function clearTimers(){clearInterval(countdown);clearTimeout(spawnTimer)}const rand=(a,b)=>Math.round(a+Math.random()*(b-a));

function questionDialog(i){const q=i>=0?clone(project.questions[i]):{id:crypto.randomUUID(),type:'single',text:'Новый вопрос',options:['Вариант 1','Вариант 2'],correct:['Вариант 1'],points:20};$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog"><div class="dialog-head"><h2>${i>=0?'Редактировать':'Новое'} задание</h2><button class="mini" data-close>×</button></div><label class="field"><span>Тип задания</span><select id="qtype"><option value="input" ${q.type==='input'?'selected':''}>Ввод ответа</option><option value="single" ${q.type==='single'?'selected':''}>Один ответ</option><option value="multiple" ${q.type==='multiple'?'selected':''}>Несколько ответов</option><option value="order" ${q.type==='order'?'selected':''}>Порядок</option></select></label><label class="field"><span>Вопрос</span><textarea id="qtext">${esc(q.text)}</textarea></label><label class="field"><span>Варианты через новую строку</span><textarea id="qoptions">${esc(q.options.join('\n'))}</textarea></label><label class="field"><span>Правильные ответы через новую строку</span><textarea id="qcorrect">${esc(q.correct.join('\n'))}</textarea></label><label class="field"><span>Очки</span><input type="number" id="qpoints" value="${q.points}"></label><button class="btn primary" id="saveQ">Сохранить задание</button></div></div>`;document.querySelector('[data-close]').onclick=()=>$('#overlay').innerHTML='';$('#saveQ').onclick=()=>{q.type=$('#qtype').value;q.text=$('#qtext').value;q.options=$('#qoptions').value.split('\n').map(x=>x.trim()).filter(Boolean);q.correct=$('#qcorrect').value.split('\n').map(x=>x.trim()).filter(Boolean);q.points=+$('#qpoints').value;if(i>=0)project.questions[i]=q;else project.questions.push(q);$('#overlay').innerHTML='';save();render()}}
function projectDialog(){$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog"><div class="dialog-head"><h2>Проект</h2><button class="mini" data-close>×</button></div><div class="row"><button class="btn" id="newP">Новый проект</button><button class="btn" id="exportJ">Экспорт JSON</button><label class="btn" style="text-align:center">Импорт JSON<input hidden type="file" id="importJ" accept="application/json"></label></div></div></div>`;$('[data-close]').onclick=()=>$('#overlay').innerHTML='';$('#newP').onclick=()=>{project=clone(defaultProject);save();render()};$('#exportJ').onclick=()=>downloadBlob(JSON.stringify(project,null,2),'bei-krota-project.json','application/json');$('#importJ').onchange=e=>{const r=new FileReader;r.onload=()=>{try{project=JSON.parse(r.result);save();render()}catch{toast('Не удалось прочитать проект')}};r.readAsText(e.target.files[0])}}
function exportDialog(){const html=generateHTML(),srcdoc=html.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;'),code=`<iframe srcdoc="${srcdoc}" width="100%" height="650" frameborder="0" allow="autoplay; fullscreen" style="width:100%;height:650px;border:0;border-radius:16px;"></iframe>`;$('#overlay').innerHTML=`<div class="modal-layer"><div class="dialog"><div class="dialog-head"><h2>${t('genially')}</h2><button class="mini" data-close>×</button></div><p class="label">Код уже содержит всю игру и настройки. Вставьте его в Genially через «Вставить → Другое → Код».</p><textarea class="code" readonly>${esc(code)}</textarea><div class="row" style="margin-top:12px"><button class="btn primary" id="copyCode">Копировать код</button><button class="btn" id="previewCode">Предпросмотр</button><button class="btn" id="downGame">${t('download')}</button></div></div></div>`;$('[data-close]').onclick=()=>$('#overlay').innerHTML='';$('#copyCode').onclick=()=>navigator.clipboard.writeText(code).then(()=>toast('Код Genially скопирован'));$('#previewCode').onclick=()=>{const u=URL.createObjectURL(new Blob([html],{type:'text/html'}));window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)};$('#downGame').onclick=downloadHTML}
function generateHTML(){const data=JSON.stringify(project).replace(/</g,'\\u003c');return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(project.meta.title)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#080c18;color:#fff;font-family:system-ui;display:grid;place-items:center;min-height:100vh}.game{position:relative;width:min(100vw,1100px);aspect-ratio:16/9;overflow:hidden;background:linear-gradient(#7ed0ea 0 35%,#71b94e 35% 44%,#8d552d 44%);${project.background.custom?`background-image:url(${project.background.custom});background-size:${project.background.fit};background-position:center`:''}}.hud{position:absolute;z-index:8;inset:15px 15px auto;display:flex;justify-content:center;gap:10px}.pill{background:#10162ddd;border:1px solid #fff3;border-radius:12px;padding:8px 14px;font-weight:800}.hole{position:absolute;transform:translate(-50%,-50%);width:16%;aspect-ratio:1.9;border-radius:50%;background:radial-gradient(ellipse,#140d08 15%,#342116 50%,#936945 54%,#59402c 68%,transparent 70%)}.char{position:absolute;z-index:3;transform:translate(-50%,-72%);font-size:clamp(42px,8vw,95px);cursor:pointer;user-select:none;filter:drop-shadow(0 8px 5px #0007);animation:up .25s}@keyframes up{from{transform:translate(-50%,-20%);opacity:0}}.cover,.modal{position:absolute;inset:0;z-index:12;display:grid;place-items:center;background:#080c19d9;backdrop-filter:blur(5px)}.card{width:min(76%,620px);padding:34px;text-align:center;background:#10182e;border:2px solid ${project.design.accent};border-radius:${project.design.radius}px;box-shadow:0 0 35px ${project.design.accent}66}.card h1{font-size:clamp(28px,5vw,55px);margin:5px}.card p{color:#c8cee2}.go,.answer{border:0;border-radius:11px;padding:13px 22px;color:#fff;background:${project.design.button};font-size:17px;font-weight:800;cursor:pointer}.answers{display:grid;grid-template-columns:1fr 1fr;gap:10px}.answer{background:#202947;border:1px solid #4c587e}.answer.sel{background:${project.design.accent}}input{width:100%;padding:14px;background:#091020;color:#fff;border:1px solid #4c587e;border-radius:10px}.fx{position:absolute;z-index:20;font-size:30px;font-weight:900;color:#ffe066;animation:fly .7s forwards}@keyframes fly{to{transform:translateY(-60px);opacity:0}}@media(max-width:650px){.game{aspect-ratio:9/16}.answers{grid-template-columns:1fr}.card{width:90%;padding:22px}}
</style></head><body><div class="game" id="game"></div><script>
const P=${data},G=document.getElementById('game');let score=0,lives=P.game.lives,time=P.game.duration,active=[],question=null,selected=[],clock,spawner;
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function title(){G.innerHTML='<div class="cover"><div class="card"><div style="font-size:65px">🦫 🔨</div><h1>'+E(P.meta.title)+'</h1><p>'+E(P.screens.subtitle)+'</p><p>'+E(P.screens.instruction)+'</p><button class="go" id="go">'+E(P.screens.playButton)+'</button></div></div>';document.getElementById('go').onclick=start}
function hud(){return '<div class="hud">'+(P.game.showTimer?'<div class="pill">⏱ '+String(Math.floor(time/60)).padStart(2,'0')+':'+String(time%60).padStart(2,'0')+'</div>':'')+(P.game.showScore?'<div class="pill">⭐ '+score+'</div>':'')+(P.game.showLives?'<div class="pill">❤️ '+lives+'</div>':'')+'</div>'}
function draw(){G.innerHTML=hud()+P.holes.map((h,i)=>'<div class="hole" style="left:'+h.x+'%;top:'+h.y+'%"></div>').join('')+active.map(a=>{const h=P.holes[a.hole],c=P.characters.find(x=>x.id===a.char);return '<div class="char" data-id="'+a.id+'" style="left:'+h.x+'%;top:'+h.y+'%">'+(c.image?'<img src="'+c.image+'" style="width:12vw;max-width:110px">':c.emoji)+'</div>'}).join('')+(question?qhtml(question):'');G.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>hit(x.dataset.id));bindQuestion()}
function start(){score=0;lives=P.game.lives;time=P.game.duration;active=[];clearInterval(clock);clearTimeout(spawner);clock=setInterval(()=>{time--;if(time<=0)end(false);else draw()},1000);spawnLoop();draw()}
function spawnLoop(){const add=()=>{if(active.length<P.spawnSettings.maxActive){let hole=Math.floor(Math.random()*P.holes.length);if(!active.some(x=>x.hole===hole)){let r=Math.random(),char=r<.12?'bomb':r<.25?'frog':'mole',a={id:Date.now()+Math.random(),hole,char};active.push(a);draw();setTimeout(()=>{active=active.filter(x=>x.id!==a.id);draw()},P.spawnSettings.visibleFor)}}spawner=setTimeout(add,P.spawnSettings.minInterval+Math.random()*(P.spawnSettings.maxInterval-P.spawnSettings.minInterval))};add()}
function hit(id){const a=active.find(x=>String(x.id)===String(id));if(!a)return;const c=P.characters.find(x=>x.id===a.char);active=active.filter(x=>x!==a);score=Math.max(0,score+c.points);if(c.kind==='danger'){lives--;if(lives<=0)return end(true)}else if(c.kind==='normal')question=P.questions[Math.floor(Math.random()*P.questions.length)];draw()}
function qhtml(q){let body=q.type==='input'?'<input id="inp" placeholder="Введите ответ">':'<div class="answers">'+q.options.map(o=>'<button class="answer" data-a="'+E(o)+'">'+E(o)+'</button>').join('')+'</div>';return '<div class="modal"><div class="card"><h3>❓ ЗАДАНИЕ</h3><h2>'+E(q.text)+'</h2>'+body+'<button class="go" id="check" style="margin-top:14px">Проверить</button></div></div>'}
function bindQuestion(){if(!question)return;G.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(question.type==='single')selected=[b.dataset.a];else selected.includes(b.dataset.a)?selected=selected.filter(x=>x!==b.dataset.a):selected.push(b.dataset.a);G.querySelectorAll('[data-a]').forEach(x=>x.classList.toggle('sel',selected.includes(x.dataset.a))) });const c=document.getElementById('check');if(c)c.onclick=check}
function check(){let ok;if(question.type==='input'){let v=document.getElementById('inp').value.trim().toLowerCase();ok=question.correct.some(x=>x.toLowerCase()===v)}else ok=question.correct.length===selected.length&&question.correct.every(x=>selected.includes(x));if(ok)score+=question.points;else lives--;question=null;selected=[];if(lives<=0)end(true);else if(score>=P.game.targetScore)end(false);else draw()}
function end(lose){clearInterval(clock);clearTimeout(spawner);G.innerHTML='<div class="cover"><div class="card"><div style="font-size:65px">'+(lose?'💔':'🏆')+'</div><h1>'+E(lose?P.screens.loseTitle:P.screens.winTitle)+'</h1><p>Результат: <b>'+score+'</b> очков</p><button class="go" id="again">Играть ещё раз</button></div></div>';document.getElementById('again').onclick=start}title();
<\/script></body></html>`}
function downloadHTML(){downloadBlob(generateHTML(),'bei-krota-game.html','text/html')}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),1800)}

document.addEventListener('click',e=>{const hitEl=e.target.closest('[data-hit]');if(hitEl&&ui.testing)hit(hitEl.dataset.hit,e)});
render();
